<?
/**
  * lookup.inc
  *
  * Lookup tables
  *
  * The lookup table is a bad idea, but it maintains compatability with TCenter1 Tickets.
  *
  * @author	David Walker	(azrail@csh.rit.edu)
  */

/* Status Defines */
$l_status[0] = "Unaccepted";
$l_status[1] = "Queued";
$l_status[2] = "In Progress";
$l_status[3] = "Pending Customer";
$l_status[4] = "Awaiting Pickup";
$l_status[5] = "Admin Hold";
$l_status[6] = "Resnet Internal"; 
$l_status[7] = "Closed";
