<?
/**
  * lookup.inc
  *
  * Lookup tables
  *
  * @author	David Walker	(azrail@csh.rit.edu)
  */

/* Status Defines */
$l_status["Unaccepted"] = 0;
$l_status["New"] = 0;
$l_status["Queued"] = 1;
$l_status["Re-Queued"] = 1;
$l_status["In Progress"] = 2;
$l_status["Pending Customer"] = 3;
$l_status["Awaiting Pickup"] = 4;
$l_status["Admin Hold"] = 5; 
$l_status["Administrative Hold"] = 5; 
$l_status["Closed"] = 6;
$l_status["Reopen"] = 6;
$l_status["1 Month Hold"] = 6;
$l_status["Reopened"] = 7;
