<?
/**
  * style.inc
  *
  */

function topCorner ()
{
?>
	<b class="corner">
		<b class="corner1">
			<b></b>
		</b>
		<b class="corner2">
			<b></b>
		</b>
		<b class="corner3"></b>
		<b class="corner4"></b>
		<b class="corner5"></b>
	</b>
	<div class="cornerfg">
<?
}

function bottomCorner ()
{
?>
	</div>
	<b class="corner">
		<b class="corner5"></b>
		<b class="corner4"></b>
		<b class="corner3"></b>
		<b class="corner2">
			<b></b>
		</b>
		<b class="corner1">
			<b></b>
		</b>
	</b>
<?
}
