<FONT size="+1">Add a hardware component</FONT>
<TABLE border="1"><FORM action="edit.php" method="post">
<TR>
  <TD><FONT size=-1>Type</FONT></TD>
  <TD><FONT size=-1><INPUT type="text" name="frmType"></FONT></TD>
</TR>
<TR>
  <TD><FONT size=-1>Model</FONT></TD>
  <TD><FONT size=-1><INPUT type="text" name="frmModel"></FONT></TD>
</TR>
<TR>
  <TD><FONT size=-1>Make</FONT></TD>
  <TD><FONT size=-1><INPUT type="text" name="frmMake"></FONT></TD>
</TR>
<TR>
  <TD><FONT size=-1>Manufacturer</FONT></TD>
  <TD><FONT size=-1><INPUT type="text" name="frmManufacturer"></FONT></TD>
</TR>

</TABLE><BR>
<INPUT type="hidden" value="insert" name="option">
<INPUT type="hidden" value="hardware" name="type">
<INPUT type="submit" value="Insert" name="frmSubmit">
<INPUT type="reset" value="Reset">
</FORM>

    
